[Issue-20] デッキ詳細ページのテキストにリッチテキストを適用
Mishima-Ryuji/ZutomayoCard pull request #23
Opened 2023-08-07 06:56 UTC by TBSten

## 目的・解決すること

close #20 

## 変更内容

 

- リッチテキストエディタ及びその表示コンポーネントを実装
- 一旦デッキ詳細ページに上記コンポーネントをプレビュー機能として適用
  - Firestoreに保存する際は**既存のフィールド( `concept` など)とは別に `markuped_xxx` フィールドを用意**しそこにテキストエディタの値を保存している。

変更ページ
- `/deck/[id]`
- `/deck/[id]/new`
- `/deck/[id]/edit`

## スクリーンショット

 

### 1. PreviewRichEditor (テキストを編集するコンポーネント)
| PC |スマホ | 
| --- | --- |
| <img width="1195" alt="スクリーンショット 2023-08-07 15 34 21" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/7bb08246-645d-4962-941e-1c32fa068876"> | スマホでログインできない（バグ？）ため未検証 |

<details>
<summary>ページ全体</summary>

![image](https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/b5e21bef-556f-4eef-a5d0-22f87b0ebd79)

</details>

### 2. RichViewer (リッチテキストを表示するコンポーネント)
| PC | スマホ | 
| --- | --- |
| <img width="542" alt="PC" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/a6073bab-387b-4522-8e9e-c2b01bae2c43"> | <img width="542" alt="スマホ" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/fa788ede-3e67-4c1a-bf07-b9fd30a3cd77"> |

<details>
<summary>ページ全体</summary>

![image](https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/bcf5b9f6-a509-4c7f-a91d-12fa3085a2e5)

</details>

## テスト項目

- [ ] スマートフォンでも動作するか確認した（影響ないと考えられる場合は省略可）
- [x] UI の変更の場合、画面サイズを変えてもレイアウトが崩れないか確認した

## チェック項目

- [x] 適切なレビュワーをアサインした。

## 備考

2023-08-07 07:01 UTC, TBSten commented
@Mishima-Ryuji 
このPRの[CI落ち](https://github.com/Mishima-Ryuji/ZutomayoCard/actions/runs/5781995135/job/15668047681?pr=23)の原因わかりますか？

ざーっとみた感じgithub actionsの権限周りの話のような気がするのですが...

2023-08-07 07:23 UTC, TBSten commented
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Updated (UTC)
> **zutomayo-card-web**	✅ Ready ([Inspect](https://vercel.com/mishima-ryuji/zutomayo-card-web/4JQa6gwoiveCNsbzFWYSLL5QEsJ9))	[Visit Preview](https://zutomayo-card-web-git-issue-20-mishima-ryuji.vercel.app)	Aug 7, 2023 6:56am

↓↓↓のURLでアクセスすると良さそうですー
https://zutomayo-card-y4w14wvlu-mishima-ryuji.vercel.app/decks/wIKbi0LhyPqcVZLUFtaj

2023-08-07 18:43 UTC, TBSten commented
> @Mishima-Ryuji このPRの[CI落ち](https://github.com/Mishima-Ryuji/ZutomayoCard/actions/runs/5781995135/job/15668047681?pr=23)の原因わかりますか？
> 
> ざーっとみた感じgithub actionsの権限周りの話のような気がするのですが...

issueの状態を更新するための権限を設定して欲しいですー

https://zenn.dev/tatsugon/articles/github-actions-permission-error

2023-08-11 05:27 UTC, Mishima-Ryuji commented
@TBSten 
>  開発時に許可されているドメインでログイン不可能なので検証不可能
この件はFirebase Authのアクセス許可ドメインによる影響だと思います。192.168.xxxをアクセス許可ドメインに足せば検証できると思います。

2023-08-11 05:28 UTC, Mishima-Ryuji commented
@TBSten 
レビューしていい状態になったらレビュワー指定お願いします。

2023-08-12 19:43 UTC, Mishima-Ryuji requested changes
レビューしました。細かいところの確認をお願いします。

2023-08-12 19:43 UTC, Mishima-Ryuji commented on web/src/components/richText/editor/RichEditor.tsx
> +export function useRichEditor({ editorKey, defaultValue }: UseRichEditorOptions) {
アロー関数でお願いします。

2023-08-12 19:43 UTC, Mishima-Ryuji commented on web/src/components/richText/editor/RichEditor.tsx
> +export default _RichEditor
export defaultは変数名を間違えたり、変数名のリファクタリングが大変になるので、使わない方針でお願いします。

2023-08-12 19:43 UTC, Mishima-Ryuji commented on web/src/components/richText/editor/RichEditor.tsx
> +const _RichEditor: FC<RichEditorProps> = ({ editorKey, onInitialize, defaultValue, placeholder = false, onDestroyed, }) => {
```suggestion
export const RichEditor: FC<RichEditorProps> = ({ editorKey, onInitialize, defaultValue, placeholder = false, onDestroyed, }) => {
```

2023-08-12 19:43 UTC, Mishima-Ryuji commented on web/src/components/richText/editor/preview/PreviewRichEditor.tsx
> +export default PreviewRichEditor
```suggestion
```

2023-08-12 19:43 UTC, Mishima-Ryuji commented on web/src/components/richText/editor/preview/PreviewRichEditor.tsx
> +const PreviewRichEditor: FC<PreviewRichEditorProps> = ({
```suggestion
export const PreviewRichEditor: FC<PreviewRichEditorProps> = ({
```

2023-08-13 17:31 UTC, TBSten commented
レビューありがとうございます🙇🏻‍♂️

2023-08-13 17:35 UTC, TBSten commented
リッチテキストエディタを色々探していたら [lexical](https://lexical.dev/)なるエディタが良さげだったのでそちらに乗り換えました。

@Mishima-Ryuji 既存実装のリファクタも含めちょっとコミット量が多くて申し訳ないんですが 再度レビューをお願いしたいです！

2023-08-13 17:37 UTC, TBSten commented on web/src/components/richText/editor/RichEditor.tsx
> +export default _RichEditor
以下コミットで対応しましたー
- [♻️ export default -> named export](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/23/commits/4cfbe4ec78142d1a7a0c430240c5f769c561f83b)

2023-08-13 17:38 UTC, TBSten commented on web/src/components/richText/editor/RichEditor.tsx
> +export function useRichEditor({ editorKey, defaultValue }: UseRichEditorOptions) {
以下コミットで対応しましたー
- [♻️ 関数定義をarrow関数に変更](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/23/commits/c67c37485b94bf731ea02ff30d01efb0a4ac5307)

2023-08-13 18:31 UTC, TBSten commented
vercel デプロイがおちてるのなんでだろう...

@Mishima-Ryuji お手数おかけしますが、Vercelのビルドログとかあれば共有お願いしたいです...!

2023-08-15 04:21 UTC, TBSten commented
> ~vercel デプロイがおちてるのなんでだろう...~
> 
> ~@ Mishima-Ryuji お手数おかけしますが、Vercelのビルドログとかあれば共有お願いしたいです...!~

こちら修正ミス発見しましたー修正してpushしましたー

2023-08-21 19:29 UTC, Mishima-Ryuji approved these changes
LGTM

2023-08-21 19:29 UTC, merged