[issue-19] Firebaseの権限エラーを回避するためデッキ詳細ページのgetStaticPropsを無効化
Mishima-Ryuji/ZutomayoCard pull request #24
Opened 2023-08-07 17:22 UTC by TBSten

## 目的・解決すること

close #19 

- 非公開のデッキの詳細ページに作成者本人がアクセスしようとしてもエラーが発生してアクセスできない件の暫定対処を実施。

## 変更内容

 

- デッキ詳細ページでのSGを無効化

## スクリーンショット

 

デザインの変更なし

## テスト項目

- [ ] スマートフォンでも動作するか確認した（影響ないと考えられる場合は省略可）
  - ログインのドメインの関係で検証不可能なのでスキップ
- [x] UI の変更の場合、画面サイズを変えてもレイアウトが崩れないか確認した

## チェック項目

- [x] 適切なレビュワーをアサインした。

## 備考

2023-08-11 05:28 UTC, Mishima-Ryuji commented
@TBSten 
確認して良い状態になったらレビュワーの指定をお願いします。

2023-08-12 19:19 UTC, Mishima-Ryuji commented
@TBSten 
Firebase Authの承認済みドメインに192.168.xxxを追加すればスマホでもログインできると思います。

2023-08-12 19:22 UTC, Mishima-Ryuji commented
@TBSten 
getStaticPropsの中でサーバー側からpermission deniedが返ってきたら、何も返さないようにしてフロント側だけで、データ取得を行ったほうがいいような気がします。これだと、全てのデッキで読み込む速度が遅くなってしまうことが気になります。お手数ですが、ご対応いただけますと幸いです。

2023-08-12 19:26 UTC, TBSten commented
> @TBSten getStaticPropsの中でサーバー側からpermission deniedが返ってきたら、何も返さないようにしてフロント側だけで、データ取得を行ったほうがいいような気がします。これだと、全てのデッキで読み込む速度が遅くなってしまうことが気になります。お手数ですが、ご対応いただけますと幸いです。

たしかに、権限ないときだけにしたほうがいいですね！対応しますー

2023-08-13 18:29 UTC, TBSten commented
> @TBSten getStaticPropsの中でサーバー側からpermission deniedが返ってきたら、何も返さないようにしてフロント側だけで、データ取得を行ったほうがいいような気がします。これだと、全てのデッキで読み込む速度が遅くなってしまうことが気になります。お手数ですが、ご対応いただけますと幸いです。

以下コミットで対応しました！
また、getStaticPropsでcardsがサーバ側で取得できた場合はclient側でそれらを利用できた方がコスト的に良さそうなので [⚡️ サーバ側でエラーが発生しても取得した値が破棄されないように修正](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/24/commits/4a6793ce2cb54e48b986976834ecd265028512ca) で途中でエラーが発生してもすでに取得できてある分はclientに返すようにしました。

- [⏪ SGするように戻した](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/24/commits/653cd658656bdca8cdf9719960031916ae0c8de1)
- [🐛 サーバ側でデッキ情報が取得できなかった時のエラーを回避](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/24/commits/2f68b80a22f026e3be740d336d1b0d407b1dd8e3)
- [⚡️ サーバ側でエラーが発生しても取得した値が破棄されないように修正](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/24/commits/4a6793ce2cb54e48b986976834ecd265028512ca)

2023-08-21 19:28 UTC, Mishima-Ryuji requested changes
細かい点だけ修正お願いします。

2023-08-21 19:28 UTC, Mishima-Ryuji commented on web/src/pages/decks/[id]/index.tsx
> +  error.code === "permission-denied"
こちら別のページでも使えるように、src/errorsとかに置いてもらえると助かります。

2023-08-22 03:21 UTC, TBSten commented on web/src/pages/decks/[id]/index.tsx
> +  error.code === "permission-denied"
対応しましたー！
[♻️ isPermissionDeniedをerrorsディレクトリに分離](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/24/commits/ab290d41bc9748a7ffdb6e4509abc48522213be0)

2023-09-09 11:05 UTC, Mishima-Ryuji approved these changes
LGTM

2023-09-09 11:05 UTC, merged