うにぐりの一言
Mishima-Ryuji/ZutomayoCard pull request #28
Opened 2023-08-21 09:09 UTC by TBSten

## 目的・解決すること

close #18 

## 変更内容

 

- ヘッダーのメニューに `/admin/uniguri-balloon` へのリンクを追加
- `/admin/uniguri-balloon` にてうにぐりの一言の管理機能

## スクリーンショット

 

### トップ

|PC|スマホ|
|---|---|
|<img width="200" alt="pc-トップ" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/d2f635d9-aee3-415a-ab26-9b08cdbf0ff1">|<img width="200" alt="sp-トップ1" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/d54e5034-399c-4bad-ba06-a2edd61fd2b1">|
| | うにぐりくんをタップする↓ |
| |<img width="200" alt="sp-トップ2" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/fd30eadf-e990-4e2f-9fd8-2b546867727a">|

### メニュー

|PC|スマホ|
|---|---|
|<img width="200" alt="pc-メニュー" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/177084d3-eeae-44ed-b490-d417cea5d4fe">|<img width="200" alt="sp-メニュー" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/c204a78a-2627-434f-8d4d-2ad7e2df6b2d">|

### 一覧画面

|PC|スマホ|
|---|---|
|<img width="200" alt="pc-一覧" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/6b416654-5250-496b-a4c2-ec9eca99e279">|<img width="200" alt="sp-一覧" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/6a8d7b2e-273c-4b0a-be76-7a10a03cef43">|

### 編集画面

|PC|スマホ|
|---|---|
|<img width="200" alt="pc-編集" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/8ec9e3d3-f8e3-4e97-89d0-a8cb838ce31f">|<img width="200" alt="sp-編集" src="https://github.com/Mishima-Ryuji/ZutomayoCard/assets/81161390/5ababf3d-bf3b-4518-89d5-50abb5aa62df">|

## テスト項目

- [x] スマートフォンでも動作するか確認した（影響ないと考えられる場合は省略可）
- [x] UI の変更の場合、画面サイズを変えてもレイアウトが崩れないか確認した

## チェック項目

- [x] 適切なレビュワーをアサインした。

## 備考

2023-08-21 19:26 UTC, Mishima-Ryuji requested changes
いい感じですね。実装ありがとうございます。ディレクトリはアンダースコア区切りで統一しているので、そこだけ修正お願いします。

2023-08-22 03:51 UTC, TBSten commented
> ディレクトリはアンダースコア区切りで統一しているので、

命名規則とかってどこかにまとまってたりしますか？

2023-08-22 13:52 UTC, TBSten commented
> ディレクトリはアンダースコア区切りで統一しているので、そこだけ修正お願いします。

対応しましたー！

- [🎨 ディレクトリのケバブケースをスネークケースに変更](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/28/commits/7d4eb7f6073dc0f697579603c7cd1233d0b5dbd2)
- [🎨 src/hooks/uniguri-balloonをスネークケースに修正](https://github.com/Mishima-Ryuji/ZutomayoCard/pull/28/commits/8bbf62fd7bd1fc30de7531429441af899e34d5e9)

2023-09-09 11:43 UTC, Mishima-Ryuji approved these changes
LGTM

2023-09-09 12:10 UTC, merged